name: Bookshelvesyoucanuse
version: '${project.version}'
main: Repohobo.BYCU.Bookshelvesyoucanuse
api-version: 1.13

commands:
  BookshelvesYouCanUse:
  BYCU:

permissions:
  BYCU.help:
    default: true
